### ISSUE TITLE
Is there a way to run this on CPU instead of CUDA GPU?

### ISSUE THREAD

**Issue by jcmvega5** [cwmok/LapIRN#1]
The machines I have access to are Windows/MacOS but neither of them have nVidia CUDA. Are there workarounds for this?

**Comment by cwmok** [comment]
Currently, there is no CPU implementation of LapIRN as training LapIRN could be extremely time-consuming with CPU. Yet, the testing scripts of LapIRN can be easily modified to CPU version by removing ".cuda()" and setting "use_cuda = False". I have attached these modified scripts as an example with this post. The scripts are tested under Windows 10 + Anaconda + Pytorch 1.7.1 (CPU).
[CPU_code.zip](https://github.com/cwmok/LapIRN/files/6106786/CPU_code.zip)
