### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by Lucas-zzy** [cwmok/LapIRN#2]
你好，耽误您一点时间，我想请问一下为什么从这里下载的训练代码可以运行，而且我检查似乎没有问题，可是为什么训练出的模型测试结果却很差？是因为我哪里没有考虑到所以没有将代码补充完整吗？因为似乎从第一级的0次模型开始，结果就远差于原始图像了。

**Comment by cwmok** [comment]
Hi Lucas, I think the problem could be related to your dataset/preprocessed pipeline. Did you normalize the intensity of your data, i.e.: [0, 1]? Could you show me your reference image and moving image that you want to register? This code has been tested with OASIS/LBPA brain dataset and three tasks in the public Learn2Reg challenge, including lung CT registration, abdominal CT registration and hippocampus registration, with promising result.

**Comment by Lucas-zzy** [comment]
Hi,Cwmok,thank you for your reply.I ran it directly based on the code downloaded from GitHub, so the data intensity was not standardized. Is intensity normalization necessary before sending the image to the model? Is there anything else that needs to be changed? My data set is a brain image with a size of 160*192*224 processed by myself. The initial similarity of the image is 0.6, but after I try to input it into the  model, it is only 0.001.So I would like to ask if there are other places in your code that I need to adjust.Thank you again for your reply.

**Comment by cwmok** [comment]
Normalizing the data intensity is important as it helps to avoid/alleviate exploding gradients during back-propagation. Besides, you should follow the training guide as written in the README.md file. After that, the network should be able to train with your own data. Also, please check out the sample image at [here](https://github.com/cwmok/LapIRN/tree/master/Data)

**Comment by Lucas-zzy** [comment]
Thank you again.
