### ISSUE TITLE
A question about LPBA40 dataset preprocessing

### ISSUE THREAD

**Issue by ChiQiuHong** [cwmok/LapIRN#23]
Hi, @cwmok 
I'm sorry to bother you, but I have some questions when I preprocessing the LPBA40 dataset. It will be highly appreciated if you can help me.

After downloading the "LPBA40 Subjects Delineation Space" dataset in loni.usc.edu,  I was confused by the image normalization. These are several ways to normalize this, and I don't know which one to use:
1. Normalize the image by the mean and std value of the image. Or
2. Scale the intensity of image to the range [0, 1]. Or
3. any other way to nomalize

Could you share your time to explain which method you used in your paper?
If you can release the preprocess code of LPBA40 or just descibe the steps in detail, that would be great.

Looking forward to your reply.

**Comment by ChiQiuHong** [comment]
OK, I just found the ***imgnorm function*** in **Code/Functions.py, line 60**
```python
def imgnorm(img):
    max_v = np.max(img)
    min_v = np.min(img)

    norm_img = (img - min_v) / (max_v - min_v)
    return norm_img
```
It seem work for me, thanks.

**Comment by cwmok** [comment]
Yes, we use "2. Scale the intensity of image to the range [0, 1]".
