### ISSUE TITLE
in the code, when SpatialTransform_unit is applied

### ISSUE THREAD

**Issue by yoonguusong** [cwmok/LapIRN#26]
Hello 

In every train, 
such as train_lvl1, train_lvl2, train_lvl3
not even this "Large deformation Diffeomorphic Image Registration with Laplacian Pyramid Networks"
but "Conditional Deformable Image Registration with Convolutional Neural Networks" github,

transform = SpatialTransform_unit().cuda()

for param in transform.parameters():
    param.requires_grad = False
    param.volatile = True

is applied even though this variable transform is not applied later in every train.

SpatialTransform_unit() is contained in the each model such as Miccai2020_LDR_laplacian_unit_add_lv1, 2, 3.

I thought if you want to apply only feed-forward, then you should put this code in the model( such as Miccai2020_LDR_laplacian_unit_add_lv1,2,3) instead of put this code outside of the model.

Of course, my opinion is wrong, but it is quite hard for me to understand.

so can I ask why you applied this?

Thank you.

**Comment by cwmok** [comment]
Hi @yoonguusong,

for param in transform.parameters():
param.requires_grad = False
param.volatile = True

The above code has no effect on the `transform`. In fact, `transform` does not have any parameters. You can simply remove it. I will clean the code later on.

**Comment by yoonguusong** [comment]
Thabk you for your comment!!!
