### ISSUE TITLE
question about grid

### ISSUE THREAD

**Issue by 18370029656** [cwmok/LapIRN#28]
Hello, may I ask what is the operation on the grid here and what is its purpose? Lines 1242 to 1244
![G@}JB(H$8% %}B3K@)A0NUX](https://github.com/cwmok/LapIRN/assets/108872700/05941dc6-d12a-4a0e-aa30-f7e557a03d7e)

**Comment by cwmok** [comment]
Hi @18370029656,

It turns an unnormalized grid into a normalized one, i.e., within [-1, 1].
