### ISSUE TITLE
LeakyReLU twice in resblock_seq?

### ISSUE THREAD

**Issue by BailiangJ** [cwmok/LapIRN#29]
Hi @cwmok ,

thanks a lot for sharing the code!

In the [resblock_seq](https://github.com/cwmok/LapIRN/blob/c17fb7564ca752d37e97baf12cafff44e01da668/Code/miccai2020_model_stage.py#L44), there is a LeakyReLU module between the PreActBlocks. While in the forward function of [PreActBlock](https://github.com/cwmok/LapIRN/blob/c17fb7564ca752d37e97baf12cafff44e01da668/Code/miccai2020_model_stage.py#L1078), another leakyrelu is called again, which means there are twice leakyrelus in between the PreActBlocks (correct me if I am wrong). 

Is this intended? 

Thank you!

**Comment by cwmok** [comment]
Hi @BailiangJ,

You're correct. It seems that the LeakyReLU modules are duplicated, which is not intended. I will clean that out later. 
Thanks for reporting the issue!
