### ISSUE TITLE
boxplot

### ISSUE THREAD

**Issue by shy922** [cwmok/LapIRN#30]
Thank you very much for your work. I still have a problem at the moment, which is how to save the csv file of the different anatomical structures to visualize boxplot during the inference phase. I see that lku has the ixi data set, but I don't know how to save the lpba40 data set, can you add this part of the code to your work? Thank you.

**Comment by cwmok** [comment]
Hi @1135451439,

I used Matplotlib `boxplot` to plot the graph. But the code was "tailor-made" to my csv files. It may not be useful for other people with different data formats in the csv file. You may find more details in https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html.
