### ISSUE TITLE
Hello, if I want to test the results of one cascade, two cascades, and three cascades respectively, what codes need to be modified?

### ISSUE THREAD

**Issue by computerAItest** [cwmok/LapIRN#31]
Hello, if I want to test the results of one cascade, two cascades, and three cascades respectively, what codes need to be modified?

**Comment by cwmok** [comment]
Hi @yuanpengpeng,

Unfortunately, it is not trivial to do so. 
You will have to 1) create models with different cascade levels and train them separately (modifying the Train_LapIRN_*.py), and 2) create your own inference code, similar to Test_LapIRN_*.py, for each model.
