### ISSUE TITLE
code 

### ISSUE THREAD

**Issue by shang-sxc** [cwmok/LapIRN#4]
I want to ask what this code means.[:,1:2,:,:,:],1:2?（down_y=cat_input_lvl1[:,1:2,:,:,:]]）.And,
I use your code to do 2D image registration, I read in B, C, h, W, less one dimension than 3D image, I want to know when you read in according to BCHW this order, if not, then what is your. Thank you very much.

**Comment by cwmok** [comment]
`down_y=cat_input_lvl1[:,1:2,:,:,:]`, where `cat_input_lvl1[:, 1:2, :, :, :]` denotes the concatenated input `x` and `y`, and in BCHWD format, `down_y` denotes the downsampled input `y` and is in BCHWD format. `cat_input_lvl1[:, 1:2, :, :, :]` This operation selects the second element in C(Channel) dimension, which is the input y.
Currently, this code supports 3D image registration only. If you want to apply it on 2D image registration, you need to change some codes such as the deformation grid size, the data size permutation, conv3D -> conv2D etc.
