### ISSUE TITLE
A question about using Train_LapIRN_diff.py

### ISSUE THREAD

**Issue by MoXiaoYing96** [cwmok/LapIRN#5]
Hi Tony! I am trying to solve a multi-modal registration question, I followed the 2020 Learn2Reg and really intrested in your method beacause your method on multi-modal registration have reached state-of-art effect.

So, I am trying to train a model by using _Train_LapIRN_diff.py_. The training was broken from the **train_lvl3** where load model, the file _../Model/LDR_OASIS_NCC_unit_add_reg_35_stagelvl2_30000.pth_ and _../Model/lossLDR_OASIS_NCC_unit_add_reg_3_anti_1_stagelvl3_10000.npy_ didn't shared to us. I replaced them to the model came frome train_lvl2 of my training, but it doesn't work because some keys is unexpected for state_dict. I am really confused.

Will you share the files? Or how to solve this problem?
Your warm answear is helping too much !

**Comment by MoXiaoYing96** [comment]
Sorry, I entered the wrong file name.
The file names of your code are "_../Model/LDR_OASIS_NCC_unit_add_reg_3_anti_1_stagelvl3_10000.pth_" and then I replace them to my training files "_../Model/LDR_OASIS_NCC_unit_add_reg_35_stagelvl2_30000.pth_".

Hope it does not affect your reading and understanding.

**Comment by cwmok** [comment]
@MoXiaoYing96 

This is actually a fatal bug in the progressive training scheme. I commented some codes for testing and forgot to add them back to my Github repository.
Basically, I missed the following code (which should be inserted in between model_lvl2 and model in line279:
    `model_path = sorted(glob.glob("../Model/Stage/" + model_name + "stagelvl2_?????.pth"))[-1]`
    `model_lvl2.load_state_dict(torch.load(model_path))`
    `print("Loading weight for model_lvl2...", model_path)`

    `# Freeze model_lvl1 weight
    for param in model_lvl2.parameters():
        param.requires_grad = False`

This is the exact code in the Train_LapIRN_disp.py as well.

The model path you are modifying is actually for training pause and resume. By default, `load_model = False` therefore it will not require the model weight file "LDR_OASIS_NCC_unit_add_reg_3_anti_1_stagelvl3_10000.pth"

I have fixed this issue and updated the Github code. Thanks for reporting the issue. :D

**Comment by cwmok** [comment]
@MoXiaoYing96 

Also, if you have finished the training on lvl1 and lvl2, you could just comment out the `train_lvl1()` and `train_lvl2()`, so that the training will skip the lvl1 and lvl2. It will automatically load your pre-trained weight for lvl1 and lvl2 and save you some time for training.

**Comment by MoXiaoYing96** [comment]
Thanks a lot! Your answer solved my problem perfectly!
Wish u have a good day~ :)

**Comment by tphankr** [comment]
> @MoXiaoYing96
> 
> Also, if you have finished the training on lvl1 and lvl2, you could just comment out the `train_lvl1()` and `train_lvl2()` at the bottom of Train_LapIRN_diff.py, so that the training will skip the lvl1 and lvl2. It will automatically load your pre-trained weight for lvl1 and lvl2 and save you some time for training.

Thank you very much, @MoXiaoYing96 @cwmok and @wingwing518,
Can you explain more if we set the "load_model=True" that will be used the weight again. What does it mean? I mean, **Are there any differences when we reuse weights**? Thank you very much.
