### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by sidank** [cwmok/LapIRN#8]
Hello again, I was curious to know whether the original OASIS dataset size of 160x192x224 will fit in this model, or do I have to crop the image size to the one mentioned in the paper (144x160x192)?

**Comment by cwmok** [comment]
@sidank 
Our model accepts 3D images with arbitrary sizes. The only thing that will bother you is the GPU memory size. If you have a decent GPU that have huge memory, you can simply use the original OASIS dataset without cropping. If not, reducing the number of feature maps for each convolution layer/the number of image registration blocks/spatial resolution of the input may help.

Please also refer to the `README.md` for more instructions, i.e.: "Train your own model" section.
